const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chao: 0},
	{Sprite: 0},
	{fundo: 0},
	{fundo2: 0},
	{janela: 0},
	{suporte: 0},
	{Flash: 0},
	{Sprite2: 0},
	{Platform: 0},
	{caixa: 0},
	{Porta: 0},
	{Jogador: 0},
	{Chave: 0},
	{Bomba: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Sprite3: 0},
	{sensorSolido: 0},
	{Teclado: 0},
	{Sprite4: 0},
	{Direcao: 0},
	{Solid: 0},
	{Inimigo: 0},
	{sensordireitapatrulha: 0},
	{sensoresquerdapatrulha2: 0},
	{inimigo_canhao: 0},
	{canhao: 0},
	{Bullet: 0},
	{DestroyOutside: 0},
	{Rotate: 0},
	{bala: 0},
	{sensorcanhao: 0},
	{Vidahud: 0},
	{Itenshud: 0},
	{blackground: 0},
	{jogadoricon: 0},
	{SpriteFont: 0},
	{chave2: 0},
	{bomba: 0},
	{Chefao: 0},
	{Audio: 0},
	{Vida: 0}
];

self.InstanceType = {
	chao: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	fundo: class extends self.ITilemapInstance {},
	fundo2: class extends self.ITilemapInstance {},
	janela: class extends self.ISpriteInstance {},
	suporte: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	sensorSolido: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	sensordireitapatrulha: class extends self.ISpriteInstance {},
	sensoresquerdapatrulha2: class extends self.ISpriteInstance {},
	inimigo_canhao: class extends self.ISpriteInstance {},
	canhao: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	sensorcanhao: class extends self.ISpriteInstance {},
	Vidahud: class extends self.ISpriteInstance {},
	Itenshud: class extends self.ISpriteInstance {},
	blackground: class extends self.ISpriteInstance {},
	jogadoricon: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	chave2: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	Chefao: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}